# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ae3830e815274f43ef72880fca0ce5ce2dc4d930443ee6bcd0f60c489cd1fcd2cc9652286dca2af301c20026208a676a4f32070ce5ed036b726df110eb578fe

test:
  secret_key_base: 233e1b5b201bf7600f34e53aaed9f2077c4d75f4742d4ecbb64bc7831246291aff787ef3e8d1c5179d8a0ba6634442579e7213e6990e80aa0003e0314c548858

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
